# Generación del modelo

## Pasar los jsonl a datos en csv para poder cargarlos en la base de datos de la API

In [139]:
import pandas as pd
import duckdb
import json

In [140]:
con = duckdb.connect('amazon_etl.db')

### Obtener libros con más de 500 reseñas

In [141]:
con.execute("""
    DROP TABLE IF EXISTS popular_books;
    CREATE TEMP TABLE popular_books AS
    SELECT parent_asin
    FROM read_json_auto('Kindle_Store.jsonl')
    GROUP BY parent_asin
    HAVING COUNT(*) >= 500;
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [142]:
total_books = con.execute("""
    SELECT COUNT(*) as total_books
    FROM popular_books
""").df()

total_books

   total_books
0         4601

### Encontrar usuarios con entre 35 y 50 reseñas dentro dichos libros

In [143]:
con.execute("""
    DROP TABLE IF EXISTS active_users;
    CREATE TEMP TABLE active_users AS
    SELECT user_id
    FROM read_json_auto('Kindle_Store.jsonl')
    WHERE parent_asin IN (SELECT parent_asin FROM popular_books)
    GROUP BY user_id
    HAVING COUNT(*) BETWEEN 35 AND 50;
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [144]:
total_users = con.execute("""
    SELECT COUNT(*) as total_users
    FROM active_users
""").df()

total_users

   total_users
0         2709

### Obtener sólo las reviews de los libros y usuarios filtrados

In [145]:
con.execute("""
    DROP TABLE IF EXISTS final_reviews;
    CREATE TEMP TABLE final_reviews AS
    SELECT user_id, parent_asin as item_id, rating, timestamp
    FROM read_json_auto('Kindle_Store.jsonl')
    WHERE parent_asin IN (SELECT parent_asin FROM popular_books)
    AND user_id IN (SELECT user_id FROM active_users);
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [146]:
total_reviews = con.execute("""
SELECT COUNT(*) as total_reviews
FROM final_reviews
""").df()

total_reviews

   total_reviews
0         111005

### Obtener metadatos de los libros seleccionados

In [147]:
con.execute("""
    DROP TABLE IF EXISTS final_meta;
    CREATE TEMP TABLE final_meta AS
    SELECT DISTINCT parent_asin as item_id, title, subtitle, description, categories, images, author
    FROM read_json_auto('meta_Kindle_Store.jsonl')
    WHERE parent_asin IN (SELECT DISTINCT item_id FROM final_reviews);
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [148]:
total_books = con.execute("""
SELECT COUNT(*) as total_books
FROM final_meta
""").df()

total_books

   total_books
0         4533

In [149]:
meta_sample = con.execute("""
    select * from final_meta
    limit 5;
""").df()

print(meta_sample.iloc[0])

item_id                                               B0019LNUVA
title          ROLLING THUNDER: An Historical Novel of War an...
subtitle                                          Kindle Edition
description    [Review, "A taut, exciting tale of good men in...
categories     [Kindle Store, Kindle eBooks, Literature & Fic...
images         [{'large': 'https://m.media-amazon.com/images/...
author         {'avatar': 'https://m.media-amazon.com/images/...
Name: 0, dtype: object

In [150]:
reviews_sample = con.execute("""
    select * from final_reviews
    limit 5;
""").df()

print(reviews_sample.iloc[0])

user_id      AHAMHLUWZTVCHUQLQNDZZAAX4KGA
item_id                        B09J8JSJL5
rating                                5.0
timestamp                   1671887532659
Name: 0, dtype: object

### Exportar a CSV

In [151]:
con.execute("COPY final_reviews TO 'kindle_reviews_seed.csv' (HEADER, DELIMITER ',')")
con.execute("COPY final_meta TO 'kindle_meta_seed.csv' (HEADER, DELIMITER ',')")
con.execute("COPY active_users TO 'active_users.csv' (HEADER, DELIMITER ',')")

In [152]:
meta_df = pd.read_csv('kindle_meta_seed.csv')

In [153]:
print(meta_df.iloc[0]['categories'])

[Kindle Store, Kindle eBooks, Literature & Fiction]

In [154]:
rows_with_unwanted_categories = meta_df[meta_df['categories'].str.contains('Kindle', na=False)]
rows_with_unwanted_categories.count()

item_id        4533
title          4533
subtitle       4155
description    4533
categories     4533
images         4533
author         4338
dtype: int64

### Mantener sólo las categorías relevantes

In [155]:
unwanted_categories = ['Kindle Store', 'Kindle eBooks', 'Kindle Unlimited', 'Kindle Short Reads', 'Kindle eTextbooks', 'Kindle Games & Active Content']
for category in unwanted_categories:
    meta_df['categories'] = meta_df['categories'].apply(lambda x: x.replace(category + ',', '') if pd.notnull(x) else x)

meta_df['categories'] = meta_df['categories'].apply(lambda x: x.replace('Kindle eBooks', '') if pd.notnull(x) else x)

meta_df['categories'] = meta_df['categories'].apply(lambda x: x.strip() if pd.notnull(x) else x)

In [156]:
rows_with_unwanted_categories = meta_df[meta_df['categories'].str.contains('Kindle', na=False)]
rows_with_unwanted_categories.count()

item_id        0
title          0
subtitle       0
description    0
categories     0
images         0
author         0
dtype: int64

In [157]:
meta_df.head()

,item_id,title,subtitle,description,categories,images,author
0,B0019LNUVA,ROLLING THUNDER: An Historical Novel of War an...,Kindle Edition,"[Review, '""A taut, exciting tale of good men i...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...
1,B076FNQWTF,The Girl Who Lived: A Thrilling Suspense Novel,Kindle Edition,"[Review, 'Praise for Christopher Greyson\'s', ...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...
2,B00FN2KR2G,The Gordonston Ladies Dog Walking Club,Kindle Edition,"[About the Author, 'The life of Duncan Whitehe...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...
3,B00QXUN5Y4,Royal Date (The Royals of Monterra Book 1),Kindle Edition,[],[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...
4,B078JDQ9BH,Defending Allye (Mountain Mercenaries Book 1),Kindle Edition,"[From the Author, 'Mountain MercenariesDefendi...",[ Romance],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...

### Limpiar la columna de imágenes

In [158]:
images = meta_df['images']

In [159]:
meta_df[meta_df['images'].str.len() < 83].__len__()

462

In [160]:
meta_df[meta_df['images'].str.len() > 83].__len__()

316

In [161]:
meta_df[meta_df['images'].str.len() > 83].iloc[0]['images']

"[{'large': 'https://m.media-amazon.com/images/I/51rUUq96UTL._SY346_.jpg', 'variant': MAIN}]"

In [162]:
meta_df[meta_df['images'].str.contains('MAIN') | meta_df['images'].str.len() < 83].__len__()

4533

In [163]:
def get_image_url(images_str):
    if images_str == '[]' or pd.isnull(images_str):
        return ''
    try:
        images_str = images_str.replace("'", '"')
        images_str = images_str.replace("MAIN", '"MAIN"')
        images = json.loads(images_str)
        for image in images:
            if image.get('variant') == 'MAIN':
                return image.get('large', '')
        return images[0].get('large', '') if images else ''
    except json.JSONDecodeError:
        return ''

In [164]:
meta_df['image_url'] = meta_df['images'].apply(get_image_url)

In [165]:
meta_df.head()

,item_id,title,subtitle,description,categories,images,author,image_url
0,B0019LNUVA,ROLLING THUNDER: An Historical Novel of War an...,Kindle Edition,"[Review, '""A taut, exciting tale of good men i...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/519YUR0HNd...
1,B076FNQWTF,The Girl Who Lived: A Thrilling Suspense Novel,Kindle Edition,"[Review, 'Praise for Christopher Greyson\'s', ...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51eAMQG-Gk...
2,B00FN2KR2G,The Gordonston Ladies Dog Walking Club,Kindle Edition,"[About the Author, 'The life of Duncan Whitehe...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51wa4udcDj...
3,B00QXUN5Y4,Royal Date (The Royals of Monterra Book 1),Kindle Edition,[],[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51B5uYHUaa...
4,B078JDQ9BH,Defending Allye (Mountain Mercenaries Book 1),Kindle Edition,"[From the Author, 'Mountain MercenariesDefendi...",[ Romance],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51ET9v-RXO...

### Cortar la descripción

In [166]:
def truncate_string(s):
    if pd.isnull(s):
        return ''
    return s[:500]

meta_df['description'] = meta_df['description'].apply(truncate_string)

### Limpiar la columna de autor

In [167]:
meta_df['author'].describe()

count                                                  4338
unique                                                 2313
top       {'avatar': 'https://m.media-amazon.com/images/...
freq                                                     29
Name: author, dtype: object

In [168]:
meta_df['author'].str.len().describe()

count     4338.000000
mean      1181.088751
std       1088.767715
min        180.000000
25%        601.000000
50%        877.000000
75%       1325.000000
max      17799.000000
Name: author, dtype: float64

In [169]:
meta_df[meta_df['author'].str.len() > 1000].iloc[700]['author']

"{'avatar': 'https://m.media-amazon.com/images/S/amzn-author-media-prod/p8nppedvfnsjaknd1htkhs445h._SY600_.jpg', 'name': Jillian Dodd, 'about': ['Jillian Dodd® a USA Today and Amazon Top 6 best-selling author. She writes fun binge-able romance series with characters her readers fall in love with—from the boy next door in the That Boy® series to the daughter of a famous actress in The Keatyn Chronicles® to a spy who might save the world in the Spy Girl® series. Her newest series include London Prep, a prep school series about a drama filled three-week exchange, and the Sex in the City-ish chick lit series, Kitty Valentine®.', 'Jillian is married to her college sweetheart, adores writing big fat happily ever afters, wears a lot of pink, buys way too many shoes, loves to travel, and is distracted by anything covered in glitter.', 'Hang out with me:', 'Join my Patreon for early versions of my work: https://www.patreon.com/jilliandodd/', 'Get early access & signed copies: www.jilliandoddstore.net', 'Text notifications: Text JILLIAN to 77222']}"

In [170]:
meta_df[meta_df['author'].str.len() > 1000].iloc[700]['author'].find(", 'about'")

132

In [171]:
def get_author_name(author_str):
    if pd.isnull(author_str):
        return 'No Disponible'
    start_idx = author_str.find("'name': ")
    if start_idx == -1:
        return 'No Disponible'
    start_idx += len("'name': ")
    end_idx = author_str.find(", 'about'", start_idx)
    return author_str[start_idx:end_idx]

In [172]:
meta_df['author_name'] = meta_df['author'].apply(get_author_name)

In [173]:
get_author_name(meta_df.iloc[0]['author'])

'Mark Berent'

In [174]:
meta_df.iloc[0]['author'].find("'name': ")

112

In [175]:
meta_df.head()

,item_id,title,subtitle,description,categories,images,author,image_url,author_name
0,B0019LNUVA,ROLLING THUNDER: An Historical Novel of War an...,Kindle Edition,"[Review, '""A taut, exciting tale of good men i...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/519YUR0HNd...,Mark Berent
1,B076FNQWTF,The Girl Who Lived: A Thrilling Suspense Novel,Kindle Edition,"[Review, 'Praise for Christopher Greyson\'s', ...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51eAMQG-Gk...,Christopher Greyson
2,B00FN2KR2G,The Gordonston Ladies Dog Walking Club,Kindle Edition,"[About the Author, 'The life of Duncan Whitehe...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51wa4udcDj...,Duncan Whitehead
3,B00QXUN5Y4,Royal Date (The Royals of Monterra Book 1),Kindle Edition,[],[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51B5uYHUaa...,Sariah Wilson
4,B078JDQ9BH,Defending Allye (Mountain Mercenaries Book 1),Kindle Edition,"[From the Author, 'Mountain MercenariesDefendi...",[ Romance],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51ET9v-RXO...,Susan Stoker

### Exportar a csv

In [176]:
books_export = meta_df[['item_id','title','subtitle','categories','author_name','image_url','description']]
books_export.to_csv('books.csv', index=False, sep='|')
books_export.head(100).to_csv('books_sample.csv', index=False, sep='|')

In [177]:
len(books_export)

4533

In [178]:
reviews_df = pd.read_csv('kindle_reviews_seed.csv')

In [179]:
reviews_df.head(100).to_csv('reviews_sample.csv', index=False)

In [180]:
reviews_df['user_id'].unique().__len__()

2709

In [181]:
reviews_df['item_id'].unique().__len__()

4533

In [182]:
reviews_df.head()

                        user_id     item_id  rating      timestamp
0  AHAMHLUWZTVCHUQLQNDZZAAX4KGA  B09J8JSJL5     5.0  1671887532659
1  AHAMHLUWZTVCHUQLQNDZZAAX4KGA  B08HN77HSL     2.0  1657888532986
2  AHAMHLUWZTVCHUQLQNDZZAAX4KGA  B08M6791DZ     5.0  1647002032110
3  AHAMHLUWZTVCHUQLQNDZZAAX4KGA  B079ZYWJJ8     5.0  1632326320291
4  AHAMHLUWZTVCHUQLQNDZZAAX4KGA  B07WHCL96K     5.0  1601307243310

In [183]:
len(reviews_df)

111005

## Generar matriz de reviews

In [188]:
import pandas as pd
from scipy.sparse import csr_matrix
from implicit.als import AlternatingLeastSquares

In [185]:
reviews_df = pd.read_csv('kindle_reviews_seed.csv')
reviews_df.head()

                        user_id     item_id  rating      timestamp
0  AHAMHLUWZTVCHUQLQNDZZAAX4KGA  B09J8JSJL5     5.0  1671887532659
1  AHAMHLUWZTVCHUQLQNDZZAAX4KGA  B08HN77HSL     2.0  1657888532986
2  AHAMHLUWZTVCHUQLQNDZZAAX4KGA  B08M6791DZ     5.0  1647002032110
3  AHAMHLUWZTVCHUQLQNDZZAAX4KGA  B079ZYWJJ8     5.0  1632326320291
4  AHAMHLUWZTVCHUQLQNDZZAAX4KGA  B07WHCL96K     5.0  1601307243310

In [237]:
meta_df = meta_df.set_index('item_id')

In [250]:
reviews_df['user_id'] = reviews_df['user_id'].astype("category")
reviews_df['item_id'] = reviews_df['item_id'].astype("category")

idx_to_userid = dict(enumerate(reviews_df['user_id'].cat.categories))
idx_to_bookid = dict(enumerate(reviews_df['item_id'].cat.categories))

userid_to_idx = { v : k for k, v in idx_to_userid.items() }
bookid_to_idx = { v : k for k, v in idx_to_bookid.items() }

def map_rating_to_confidence(rating):
    if rating >= 4:
        return 1.0
    elif rating == 3:
        return 0.5
    else:
        return 0.0

user_item_matrix = csr_matrix(
    (reviews_df['rating'].astype(float).apply(map_rating_to_confidence), (user_indices, book_indices)),
    shape=(len(reviews_df['user_id'].cat.categories), len(reviews_df['item_id'].cat.categories))
)

In [251]:
user_item_matrix.shape

(2709, 4533)

In [252]:
model = AlternatingLeastSquares(factors=50, regularization=0.01, iterations=20)
model.fit(user_item_matrix)

  0%|          | 0/20 [00:00<?, ?it/s]

In [253]:
print(idx_to_userid[0])
print(userid_to_idx[idx_to_userid[0]])
print(userid_to_idx[idx_to_userid[0]] == 0)

AE22PJ54OVIRX3I6KSLMPRHPHA4A
0
True

In [254]:
# Get recommendations for the a single user
userid = 0
ids, scores = model.recommend(userid, user_item_matrix[userid], N=10, filter_already_liked_items=False)
book_ids = [idx_to_bookid[id] for id in ids]
print("Recommended book IDs for user {}: {}".format(idx_to_userid[userid], book_ids))

Recommended book IDs for user AE22PJ54OVIRX3I6KSLMPRHPHA4A: ['B00K2EOONI', 'B00BVFM04C', 'B00NAJZDIM', 'B00LXRJICK', 'B00LWE0QZM', 'B0186N2W9Y', 'B007FG9LIE', 'B00TEFTA80', 'B01MRXR9S2', 'B00PM995TG']

In [255]:
meta_df.loc[book_ids]

,title,subtitle,description,categories,images,author,image_url,author_name
item_id,,,,,,,,
B00K2EOONI,My Sister's Grave (Tracy Crosswhite Book 1),Kindle Edition,"[Review, A Goodreads Best Book of the Month, “...","[ 'Mystery, Thriller & Suspense']",[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/61mGjcb5IB...,Robert Dugoni
B00BVFM04C,Breakthrough,Kindle Edition,"[Review, '""If you like Clive Cussler you will ...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51NJsE4WKL...,Michael C. Grumley
B00NAJZDIM,Wreckage,Kindle Edition,"[From the Publisher, 'You know that chill you ...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/41svUp30fP...,Emily Bleeker
B00LXRJICK,Leap (Breakthrough Book 2),NaN,"[From the Author, 'THE COMPLETE BREAKTHROUGH S...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/518NkQMh-X...,Michael C. Grumley
B00LWE0QZM,The Dead Key,NaN,"[From Publishers Weekly, 'This superb novel te...","[ 'Mystery, Thriller & Suspense']",[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/510dmgue3L...,D. M. Pulley
B0186N2W9Y,Catalyst (Breakthrough Book 3),Kindle Edition,"[From the Author, 'THE COMPLETE BREAKTHROUGH S...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51r2eWaUIa...,Michael C. Grumley
B007FG9LIE,"Pines (The Wayward Pines Trilogy, Book 1)",NaN,"[Amazon.com Review, Blake Crouch on How the Te...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/41TiX1qlqj...,Blake Crouch
B00TEFTA80,Her Final Breath (Tracy Crosswhite Book 2),Kindle Edition,"[Review, 'Amazon Best Book of the Month, Myste...","[ 'Mystery, Thriller & Suspense']",[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51mcyr3a8f...,Robert Dugoni
B01MRXR9S2,Ripple (Breakthrough Book 4),Kindle Edition,"[From the Author, 'THE COMPLETE BREAKTHROUGH S...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/510O3luceh...,Michael C. Grumley
B00PM995TG,The Einstein Prophecy,Kindle Edition,"[Review, '“A page-turner offering up a wealth ...","[ 'Mystery, Thriller & Suspense']",[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51z7sppbsZ...,Robert Masello

In [256]:
import numpy as np
import pandas as pd
pd.DataFrame({"Book": meta_df.loc[book_ids]['title'], "score": scores, "already_liked": np.in1d(ids, user_item_matrix[userid].indices)})

,Book,score,already_liked
item_id,,,
B00K2EOONI,My Sister's Grave (Tracy Crosswhite Book 1),0.951658,True
B00BVFM04C,Breakthrough,0.695341,True
B00NAJZDIM,Wreckage,0.621723,True
B00LXRJICK,Leap (Breakthrough Book 2),0.561169,True
B00LWE0QZM,The Dead Key,0.520448,False
B0186N2W9Y,Catalyst (Breakthrough Book 3),0.419310,True
B007FG9LIE,"Pines (The Wayward Pines Trilogy, Book 1)",0.371441,True
B00TEFTA80,Her Final Breath (Tracy Crosswhite Book 2),0.361116,False
B01MRXR9S2,Ripple (Breakthrough Book 4),0.328329,False
B00PM995TG,The Einstein Prophecy,0.316306,False

In [257]:
bookid_to_idx

{'B000FA5PZU': 0,
 'B000FA5QMM': 1,
 'B000FA5SMK': 2,
 'B000FA5SPW': 3,
 'B000FA5STS': 4,
 'B000FA5SUM': 5,
 'B000FA64R8': 6,
 'B000FA670W': 7,
 'B000FBFMB6': 8,
 'B000FBFMFM': 9,
 'B000FBFMFW': 10,
 'B000FBFMG6': 11,
 'B000FBFMZ2': 12,
 'B000FBFMZM': 13,
 'B000FBFN1U': 14,
 'B000FBFNME': 15,
 'B000FBFNT2': 16,
 'B000FBJAEQ': 17,
 'B000FBJCJE': 18,
 'B000FBJCK8': 19,
 'B000FBJDF2': 20,
 'B000FBJFSC': 21,
 'B000FBJFSM': 22,
 'B000FBJGEK': 23,
 'B000FBJHKI': 24,
 'B000FBJHZS': 25,
 'B000FC0PDA': 26,
 'B000FC0QBQ': 27,
 'B000FC0QHA': 28,
 'B000FC0SH8': 29,
 'B000FC0SJ6': 30,
 'B000FC0STQ': 31,
 'B000FC0VVQ': 32,
 'B000FC0ZIA': 33,
 'B000FC10S4': 34,
 'B000FC11A6': 35,
 'B000FC128M': 36,
 'B000FC130E': 37,
 'B000FC13Y0': 38,
 'B000FC146C': 39,
 'B000FC14JY': 40,
 'B000FC1AGG': 41,
 'B000FC1BNI': 42,
 'B000FC1HBY': 43,
 'B000FC1IRM': 44,
 'B000FC1KKC': 45,
 'B000FC1MBO': 46,
 'B000FC1MCS': 47,
 'B000FC1PWA': 48,
 'B000FC1RSC': 49,
 'B000FC1SCW': 50,
 'B000FC2L1E': 51,
 'B000FC2L1O': 52,
 'B000FC2L1Y': 53,
 'B000FC2L28': 54,
 'B000FC2MAO': 55,
 'B000FCJYH8': 56,
 'B000FCK2TW': 57,
 'B000FCK2VK': 58,
 'B000FCK3C8': 59,
 'B000FCK5PI': 60,
 'B000FCK5YE': 61,
 'B000FCK6EI': 62,
 'B000FCKB48': 63,
 'B000FCKENQ': 64,
 'B000FCKFGW': 65,
 'B000FCKG1G': 66,
 'B000FCKGMA': 67,
 'B000FCKGPC': 68,
 'B000FCKGVG': 69,
 'B000FCKH56': 70,
 'B000FCKLWU': 71,
 'B000FCKPHG': 72,
 'B000FCKPJE': 73,
 'B000GCFBQA': 74,
 'B000GCFG7E': 75,
 'B000JMKNJ2': 76,
 'B000JMKQX0': 77,
 'B000JMKR4S': 78,
 'B000JMKRKC': 79,
 'B000JMKTLO': 80,
 'B000JMKV9Y': 81,
 'B000JMLFLW': 82,
 'B000MAH7SQ': 83,
 'B000N2HBSO': 84,
 'B000NY12LO': 85,
 'B000O76NMS': 86,
 'B000O76ON6': 87,
 'B000OCXGZA': 88,
 'B000OCXHTK': 89,
 'B000OCXJPM': 90,
 'B000OI0FVW': 91,
 'B000OI0G1Q': 92,
 'B000OIZSKA': 93,
 'B000OIZTAO': 94,
 'B000OT8GD0': 95,
 'B000OVLIRE': 96,
 'B000OVLK2W': 97,
 'B000OVLKMM': 98,
 'B000OZ0NWQ': 99,
 'B000P2A47M': 100,
 'B000PDYVU2': 101,
 'B000PLXEU2': 102,
 'B000Q9IN4K': 103,
 'B000Q9INB8': 104,
 'B000Q9ITGW': 105,
 'B000QCQ8Y4': 106,
 'B000QCS8TW': 107,
 'B000QCS9PA': 108,
 'B000QJLQZI': 109,
 'B000QRIGJ4': 110,
 'B000QRIGKI': 111,
 'B000QRIGLC': 112,
 'B000QRIGLW': 113,
 'B000QTE9WU': 114,
 'B000QUCO12': 115,
 'B000RH0E70': 116,
 'B000S1LSAM': 117,
 'B000SCHC0Q': 118,
 'B000SEFNMS': 119,
 'B000SEFOKO': 120,
 'B000SEGE6M': 121,
 'B000SEGTI0': 122,
 'B000SEGUDE': 123,
 'B000SEH16E': 124,
 'B000SEHPJW': 125,
 'B000SEI1EA': 126,
 'B000SEI230': 127,
 'B000SEI5CI': 128,
 'B000SEIK2S': 129,
 'B000SEK2CY': 130,
 'B000SEVYSA': 131,
 'B000T8F50S': 132,
 'B000TO0TDK': 133,
 'B000U0O9FM': 134,
 'B000UZJQXM': 135,
 'B000UZNR32': 136,
 'B000UZNSN6': 137,
 'B000UZPIE8': 138,
 'B000UZQI0Q': 139,
 'B000V77082': 140,
 'B000VMFDW2': 141,
 'B000VRBBD2': 142,
 'B000W4RFBQ': 143,
 'B000W8HC8I': 144,
 'B000W9399S': 145,
 'B000W93CHC': 146,
 'B000W94FU0': 147,
 'B000XGMTWS': 148,
 'B000XUBC2C': 149,
 'B000XUBFE2': 150,
 'B000YI1K0C': 151,
 'B000YJ54DU': 152,
 'B0010SGRMG': 153,
 'B0010SIPT4': 154,
 'B0010SKUYM': 155,
 'B0011UCPLU': 156,
 'B0011UGLRY': 157,
 'B0011UJM48': 158,
 'B0013380Z0': 159,
 'B00139VU7E': 160,
 'B0013TRR80': 161,
 'B0013TTLDE': 162,
 'B0013TXA5Y': 163,
 'B0014H32E4': 164,
 'B0015DPX7G': 165,
 'B0015DYIH2': 166,
 'B00166J8KA': 167,
 'B00179FNRI': 168,
 'B0017SWPXY': 169,
 'B0018QOYKC': 170,
 'B0018QQQK8': 171,
 'B0019LNUVA': 172,
 'B0019SW4DS': 173,
 'B001ANSS5K': 174,
 'B001ANSSDC': 175,
 'B001BC5HXG': 176,
 'B001BZRUR4': 177,
 'B001C4NXKM': 178,
 'B001CK7YV0': 179,
 'B001DA9J4O': 180,
 'B001FA0TT6': 181,
 'B001FA0U3G': 182,
 'B001FXK8XU': 183,
 'B001GA1RFA': 184,
 'B001GUXJN8': 185,
 'B001GUXJQU': 186,
 'B001GUXJSI': 187,
 'B001GXF2S0': 188,
 'B001I45UF2': 189,
 'B001I45UFC': 190,
 'B001IG9D6M': 191,
 'B001KDQ4KQ': 192,
 'B001L83PM0': 193,
 'B001MBU7EK': 194,
 'B001NLKV7C': 195,
 'B001NLKXK2': 196,
 'B001NLKZUA': 197,
 'B001NLL414': 198,
 'B001NLL5AO': 199,
 'B001NLL6QW': 200,
 'B001NLL82Y': 201,
 'B001NLL8LA': 202,
 'B001NLL93W': 203,
 'B001O1O71C': 204,
 'B001OLRMZA': 205,
 'B001PSEPLG': 206,
 'B001PSEPZW': 207,
 'B001Q9J4PG': 208,
 'B001QEAQP8': 209,
 'B001QEAQQC': 210,
 'B001QEAQQW': 211,
 'B001QNVPKY': 212,
 'B001QS9TSE': 213,
 'B001R11CJO': 214,
 'B001SR66K2': 215,
 'B001UFP6JY': 216,
 'B001UID8DM': 217,
 'B001VH6N02': 218,
 'B001VLXNLU': 219,
 'B0020BUWX2': 220,
 'B002361MLA': 221,
 'B0023SDPS6': 222,
 'B00264FT0Y': 223,
 'B00267T89E': 224,
 'B0026LTNFO': 225,
 'B0026RI9TO': 226,
 'B0026SCMNM': 227,
 'B00276HAEY': 228,
 'B00280LYHI': 229,
 'B00280LYHS': 230,
 'B00280LYIC': 231,
 'B00280LYIM': 232,
 'B0028MBKVG': 233,
 'B002AKPELI': 234,
 'B002ASFQ3G': 235,
 'B002AU7MJU': 236,
 'B002AWX6UM': 237,
 'B002BD2UR0': 238,
 'B002BD2US4': 239,
 'B002BD2V2Y': 240,
 'B002BD2V38': 241,
 'B002BSHHTQ': 242,
 'B002DOSBMK': 243,
 'B002DW92UC': 244,
 'B002FDLOFU': 245,
 'B002FK3U4Q': 246,
 'B002GEDEKQ': 247,
 'B002GYI9C4': 248,
 'B002H8ORMU': 249,
 'B002HHPVBC': 250,
 'B002HJV79U': 251,
 'B002HPRBZS': 252,
 'B002JWD6AS': 253,
 'B002KP6DXQ': 254,
 'B002KYHZHA': 255,
 'B002KYHZLQ': 256,
 'B002L6HE46': 257,
 'B002LA0A8O': 258,
 'B002LATV16': 259,
 'B002LC8HF0': 260,
 'B002LHRLNE': 261,
 'B002M2AT0K': 262,
 'B002M5E2DW': 263,
 'B002MBLU9U': 264,
 'B002MQYOFW': 265,
 'B002N83GSA': 266,
 'B002NC733U': 267,
 'B002NXOQF2': 268,
 'B002OHD1WQ': 269,
 'B002PDOOOI': 270,
 'B002PMVY3I': 271,
 'B002Q1YDKO': 272,
 'B002Q7H7JC': 273,
 'B002QE3CTY': 274,
 'B002RLBKIQ': 275,
 'B002SR2PKG': 276,
 'B002SRL3F4': 277,
 'B002SRL3PO': 278,
 'B002T9U302': 279,
 'B002TS77XY': 280,
 'B002TWIVNA': 281,
 'B002TXZS8A': 282,
 'B002U3CCYM': 283,
 'B002U5HKZ6': 284,
 'B002UBRFDC': 285,
 'B002UM5BXW': 286,
 'B002VBV1R2': 287,
 'B002WAUV7S': 288,
 'B002WE46VG': 289,
 'B002WGC8JG': 290,
 'B002YKOXB6': 291,
 'B002Z13UGS': 292,
 'B002Z7G0QO': 293,
 'B003062GEE': 294,
 'B0030AF5DO': 295,
 'B0030AOBR0': 296,
 'B0030CVQMG': 297,
 'B0030H7UIU': 298,
 'B0030V0PEW': 299,
 'B0030ZRZ7S': 300,
 'B0031B7KCQ': 301,
 'B0031R5JSM': 302,
 'B00329UWL8': 303,
 'B0032UY4FW': 304,
 'B0034DGPEU': 305,
 'B0035II952': 306,
 'B00362XLI2': 307,
 'B0036FTF4S': 308,
 'B0036G8IQS': 309,
 'B0036S4B6M': 310,
 'B0036S4C6G': 311,
 'B0036S4CEI': 312,
 'B0036S4CPW': 313,
 'B0036S4CWA': 314,
 'B0036Z9W00': 315,
 'B0037Z6Z9K': 316,
 'B0038AUY8M': 317,
 'B0038B99PK': 318,
 'B00394F3TM': 319,
 'B00395ZYY0': 320,
 'B0039UUB16': 321,
 'B003A022YO': 322,
 'B003A7I22S': 323,
 'B003ATPRNI': 324,
 'B003B02OOG': 325,
 'B003B02P9U': 326,
 'B003BQZ83O': 327,
 'B003D8V7DK': 328,
 'B003DKJ9Q0': 329,
 'B003E8P9G0': 330,
 'B003EJDGBO': 331,
 'B003EY7IRC': 332,
 'B003EY7IWC': 333,
 'B003F1WMCK': 334,
 'B003F3FJQO': 335,
 'B003F3PM7A': 336,
 'B003G4W49C': 337,
 'B003G93YLY': 338,
 'B003GFIW3S': 339,
 'B003GWX8SK': 340,
 'B003GY0K48': 341,
 'B003GYEGMU': 342,
 'B003H4I46I': 343,
 'B003H4I4JU': 344,
 'B003H4I58K': 345,
 'B003I1WY20': 346,
 'B003I1WY2A': 347,
 'B003IEJZRY': 348,
 'B003IGDD7A': 349,
 'B003IPDMAE': 350,
 'B003JFJHOS': 351,
 'B003JFJHRK': 352,
 'B003JFJHTS': 353,
 'B003JH8GAC': 354,
 'B003JMF4FC': 355,
 'B003JMFKRE': 356,
 'B003JMFKVK': 357,
 'B003JTHMO6': 358,
 'B003JTHWKK': 359,
 'B003JTHWKU': 360,
 'B003JTHXOK': 361,
 'B003JTHY76': 362,
 'B003K15IF8': 363,
 'B003K15IJE': 364,
 'B003K16P3M': 365,
 'B003K16PBE': 366,
 'B003K16PUU': 367,
 'B003K16PXC': 368,
 'B003K16Q3G': 369,
 'B003KGAUUQ': 370,
 'B003KN3MDG': 371,
 'B003KVL35W': 372,
 'B003L7861E': 373,
 'B003LSTK8G': 374,
 'B003MC5N28': 375,
 'B003N3UZHY': 376,
 'B003NE6HD4': 377,
 'B003NX764O': 378,
 'B003NX76BM': 379,
 'B003O2SQO8': 380,
 'B003O86FMW': 381,
 'B003OUXE7Y': 382,
 'B003P2QCE8': 383,
 'B003P2W1JI': 384,
 'B003P2WO5E': 385,
 'B003P37FW0': 386,
 'B003P38AAG': 387,
 'B003P8Q5QC': 388,
 'B003P9VZF2': 389,
 'B003P9XMFI': 390,
 'B003PPDB8K': 391,
 'B003QCIPGK': 392,
 'B003R0LBVC': 393,
 'B003RRXXMA': 394,
 'B003RWS5Q4': 395,
 'B003SE75ZS': 396,
 'B003SE7O40': 397,
 'B003TFETP0': 398,
 'B003TO5GXU': 399,
 'B003TSEL7S': 400,
 'B003TU29WA': 401,
 'B003UBTX6S': 402,
 'B003UBTX72': 403,
 'B003UHVYQE': 404,
 'B003UV90G6': 405,
 'B003UV988Q': 406,
 'B003UV98BI': 407,
 'B003UV98MM': 408,
 'B003UYUP26': 409,
 'B003UYURXS': 410,
 'B003V1WVH0': 411,
 'B003V1WXKU': 412,
 'B003V8B5XO': 413,
 'B003WEAI4E': 414,
 'B003WJQ74E': 415,
 'B003WUYQ64': 416,
 'B003X28734': 417,
 'B003X95M94': 418,
 'B003XF1XOQ': 419,
 'B003XKN65U': 420,
 'B003XKNWHM': 421,
 'B003XVYJ2S': 422,
 'B003XVYLDU': 423,
 'B003Y3BCRU': 424,
 'B003Y3BCS4': 425,
 'B003Y5H8IK': 426,
 'B003YCPF88': 427,
 'B003YCPJJI': 428,
 'B003YL4LNY': 429,
 'B003YL4LYI': 430,
 'B003YOSCA4': 431,
 'B003YUC3YE': 432,
 'B003ZDP194': 433,
 'B003ZK58SQ': 434,
 'B003ZUYQCA': 435,
 'B003ZX868W': 436,
 'B003ZYEXGA': 437,
 'B00400MQ9Y': 438,
 'B00413PT8A': 439,
 'B00413QAJM': 440,
 'B004183KI6': 441,
 'B0041T52UY': 442,
 'B00422LESO': 443,
 'B00427ZI2C': 444,
 'B00428LBDQ': 445,
 'B0042FZWZ2': 446,
 'B0042P5DA6': 447,
 'B0042XA3OE': 448,
 'B00433TO4I': 449,
 'B0043M4ZH0': 450,
 'B004443YV0': 451,
 'B004477WN8': 452,
 'B0044DEL22': 453,
 'B0044KM17M': 454,
 'B0045JLR5Y': 455,
 'B0045UA66Y': 456,
 'B0045Y1N12': 457,
 'B00466H8JK': 458,
 'B0046ECFKE': 459,
 'B0046XRKJ6': 460,
 'B00475ARQG': 461,
 'B00475AYJQ': 462,
 'B0047DX080': 463,
 'B0047Y0FGY': 464,
 'B0047Y171G': 465,
 'B00495XOWS': 466,
 'B0049H92G8': 467,
 'B0049U4W56': 468,
 'B004A90BXS': 469,
 'B004AM5R48': 470,
 'B004BDOZZI': 471,
 'B004BSGJFW': 472,
 'B004C43I68': 473,
 'B004C44556': 474,
 'B004C6S25I': 475,
 'B004CFA91Y': 476,
 'B004CFA9R8': 477,
 'B004CFA9RS': 478,
 'B004CFAWK2': 479,
 'B004CLYL2Q': 480,
 'B004CLYLAI': 481,
 'B004CR6AM4': 482,
 'B004D9FUA4': 483,
 'B004DCB32K': 484,
 'B004DERF5M': 485,
 'B004DI7HZ6': 486,
 'B004DWEL0Q': 487,
 'B004DWLGGS': 488,
 'B004EBTGDS': 489,
 'B004EHZXVQ': 490,
 'B004EPYUXA': 491,
 'B004EPYYDQ': 492,
 'B004EVRX1A': 493,
 'B004EYTK2C': 494,
 'B004FGMDOQ': 495,
 'B004FN1P1Q': 496,
 'B004FPZ272': 497,
 'B004FPZ588': 498,
 'B004FV58Z2': 499,
 'B004G606EO': 500,
 'B004G606K8': 501,
 'B004G60EHS': 502,
 'B004G8QZSS': 503,
 'B004GB1T8G': 504,
 'B004GHND6Q': 505,
 'B004GHNGKE': 506,
 'B004GHNIQQ': 507,
 'B004GHNIRK': 508,
 'B004GKMY7C': 509,
 'B004GKNLMY': 510,
 'B004H1TDB0': 511,
 'B004H1TQBW': 512,
 'B004H1UOSG': 513,
 'B004H4XCTQ': 514,
 'B004H4XDBI': 515,
 'B004H8FVEQ': 516,
 'B004HB1W82': 517,
 'B004HD5TV6': 518,
 'B004HD61L8': 519,
 'B004HFRJCG': 520,
 'B004HFRJM6': 521,
 'B004HYHAVM': 522,
 'B004I437ZO': 523,
 'B004I6DD7E': 524,
 'B004I8WNWI': 525,
 'B004IPQE0I': 526,
 'B004IYITJ8': 527,
 'B004IYJDVG': 528,
 'B004IZLRU0': 529,
 'B004J17GY4': 530,
 'B004J4WKOW': 531,
 'B004J4WKTW': 532,
 'B004J4WKUQ': 533,
 'B004J4WKXS': 534,
 'B004J4WKY2': 535,
 'B004J4WL2I': 536,
 'B004J4WLB4': 537,
 'B004J4WLIM': 538,
 'B004J4WN0I': 539,
 'B004J4WNL2': 540,
 'B004J4X33O': 541,
 'B004J4X7JO': 542,
 'B004J4XA6E': 543,
 'B004J8HSCC': 544,
 'B004JHYA6A': 545,
 'B004JN1CW4': 546,
 'B004JN1D2I': 547,
 'B004JN1D3M': 548,
 'B004KKXWMO': 549,
 'B004KKY782': 550,
 'B004KSQDEA': 551,
 'B004KZP1WS': 552,
 'B004KZPK92': 553,
 'B004L62E08': 554,
 'B004LB4FBE': 555,
 'B004LB5BR6': 556,
 'B004LROPC2': 557,
 'B004LROUW2': 558,
 'B004LX0FYS': 559,
 'B004M18ZRS': 560,
 'B004MME1RU': 561,
 'B004MYFNIO': 562,
 'B004N6379S': 563,
 'B004NNVEHI': 564,
 'B004O4C074': 565,
 'B004O4C1AK': 566,
 'B004OA62VS': 567,
 'B004OA64H0': 568,
 'B004OL2OKK': 569,
 'B004P8JPS6': 570,
 'B004PLNIFE': 571,
 'B004PYDGBM': 572,
 'B004Q7CIFI': 573,
 'B004QOAZO2': 574,
 'B004QTOIJA': 575,
 'B004QWZCYC': 576,
 'B004QX076Y': 577,
 'B004QX07EG': 578,
 'B004QX07EQ': 579,
 'B004QX07G4': 580,
 'B004QZ9PE2': 581,
 'B004QZ9PLU': 582,
 'B004R1PVR0': 583,
 'B004R1Q6B0': 584,
 'B004RCNS9C': 585,
 'B004RD856M': 586,
 'B004RJ7Y8Q': 587,
 'B004RPMYF8': 588,
 'B004RQ00Q2': 589,
 'B004RR1NZI': 590,
 'B004RZ2660': 591,
 'B004S1WMHG': 592,
 'B004S3HWJ2': 593,
 'B004S7EUJ8': 594,
 'B004S7FB4G': 595,
 'B004S7XCTW': 596,
 'B004S87M92': 597,
 'B004SBO41S': 598,
 'B004SUO5JA': 599,
 'B004SUP1XO': 600,
 'B004T3AXEW': 601,
 'B004T4KXYQ': 602,
 'B004T4LQMY': 603,
 'B004T4UNU0': 604,
 'B004TCSMQY': 605,
 'B004TMPMJE': 606,
 'B004TNIXYY': 607,
 'B004TP5JXA': 608,
 'B004TP8ZZE': 609,
 'B004TPCQWC': 610,
 'B004TRFNIE': 611,
 'B004TRXX7C': 612,
 'B004TS1MGK': 613,
 'B004TS2B4W': 614,
 'B004U2UPOK': 615,
 'B004U34BZS': 616,
 'B004U7HRT6': 617,
 'B004U7HSV8': 618,
 'B004UB0WTY': 619,
 'B004UHLJFO': 620,
 'B004UI0NVE': 621,
 'B004UJ7VJU': 622,
 'B004UJAOLM': 623,
 'B004UJCNKC': 624,
 'B004UJDLJE': 625,
 'B004UJTG6Q': 626,
 'B004ULORYU': 627,
 'B004ULVGPI': 628,
 'B004V49BLU': 629,
 'B004VMV412': 630,
 'B004VS2WPS': 631,
 'B004W0COEY': 632,
 'B004W2UBYW': 633,
 'B004W3IEI6': 634,
 'B004WDRYVE': 635,
 'B004WOX12O': 636,
 'B004WPP8YW': 637,
 'B004WY3D0O': 638,
 'B004XDACV2': 639,
 'B004XDWJ18': 640,
 'B004XFYN9M': 641,
 'B004XFYWNY': 642,
 'B004XFZ8X2': 643,
 'B004XJ4NI4': 644,
 'B004XJRQUQ': 645,
 'B004XQVC6I': 646,
 'B004XT6L8E': 647,
 'B004XVN0WW': 648,
 'B004XVN82Y': 649,
 'B004XWBUKK': 650,
 'B004XWPWPE': 651,
 'B004Y1NWQU': 652,
 'B004YDSL9Q': 653,
 'B004YKZIGI': 654,
 'B004YTI17M': 655,
 'B004YW4L5K': 656,
 'B004YWKKEG': 657,
 'B004Z1DBG0': 658,
 'B004Z4IKMM': 659,
 'B004Z8D7TY': 660,
 'B004ZCIG64': 661,
 'B004ZGI1HO': 662,
 'B004ZMWUCU': 663,
 'B004ZY0VHY': 664,
 'B004ZZH4V4': 665,
 'B00505AZRS': 666,
 'B0050KJGLO': 667,
 'B0050ON37S': 668,
 'B0050PJZLK': 669,
 'B0050Q5WYS': 670,
 'B00514HDNW': 671,
 'B0051ANPZQ': 672,
 'B0051ANRMW': 673,
 'B0051BBHGE': 674,
 'B0051GTA2C': 675,
 'B0051PRFLQ': 676,
 'B00526VVN2': 677,
 'B0052DNX40': 678,
 'B0052RDH6K': 679,
 'B0052RDJAO': 680,
 'B0052RE4MQ': 681,
 'B0052T1O6S': 682,
 'B0052UX1KE': 683,
 'B0052XQ068': 684,
 'B0053CYXS0': 685,
 'B0053GQYTM': 686,
 'B0053HWAWQ': 687,
 'B0053JJLLC': 688,
 'B0053TMP24': 689,
 'B00540QR7Q': 690,
 'B00546IDUY': 691,
 'B0054R6BFM': 692,
 'B0054TVO0M': 693,
 'B00555X8OA': 694,
 'B005563J7A': 695,
 'B005569HMG': 696,
 'B0055FDRH8': 697,
 'B0055I10H4': 698,
 'B0055PGUYU': 699,
 'B0055PJHPY': 700,
 'B0055PMRSS': 701,
 'B0055T19MO': 702,
 'B0055TFNWG': 703,
 'B0055UP87U': 704,
 'B0055UZO9M': 705,
 'B0055WY7O8': 706,
 'B0055X0OLM': 707,
 'B00560R3WM': 708,
 'B005723JSQ': 709,
 'B005723K2Q': 710,
 'B0057AMO2A': 711,
 'B0057P6FNO': 712,
 'B0057QO8Q4': 713,
 'B0057XY24K': 714,
 'B00589BAWK': 715,
 'B0058I8A6K': 716,
 'B0058UXHHK': 717,
 'B005983WCQ': 718,
 'B0059AJ8V8': 719,
 'B005A1JBB8': 720,
 'B005ALW6GU': 721,
 'B005BOXICM': 722,
 'B005BOXJK8': 723,
 'B005BVM9YI': 724,
 'B005BYPLPE': 725,
 'B005C1N24I': 726,
 'B005C2COA0': 727,
 'B005C2SOQ8': 728,
 'B005C5YZ86': 729,
 'B005CHQY24': 730,
 'B005COO1X6': 731,
 'B005CRQ2DK': 732,
 'B005CRQ2OE': 733,
 'B005CRQ3NY': 734,
 'B005CRQ3RK': 735,
 'B005CRQ4GU': 736,
 'B005CRQ4OW': 737,
 'B005CRQ4XI': 738,
 'B005CXI8I6': 739,
 'B005D24RYU': 740,
 'B005DJ93EW': 741,
 'B005DJHWRW': 742,
 'B005ECT8DO': 743,
 'B005EHR1EW': 744,
 'B005EHRSUY': 745,
 'B005EIO02C': 746,
 'B005ENBASO': 747,
 'B005EU50HY': 748,
 'B005FA2YXG': 749,
 'B005FI2EA6': 750,
 'B005FXZP9S': 751,
 'B005GG0M0G': 752,
 'B005GG0MBU': 753,
 'B005GG0MIS': 754,
 'B005GG0MTC': 755,
 'B005GSZIZS': 756,
 'B005GSZZKG': 757,
 'B005GY0Y8S': 758,
 'B005HF2V3W': 759,
 'B005HFNWJO': 760,
 'B005HISY0I': 761,
 'B005HXFVGS': 762,
 'B005I044WW': 763,
 'B005IEGU2U': 764,
 'B005IQHS7E': 765,
 'B005IQZB14': 766,
 'B005IRPSM0': 767,
 'B005IYEQKI': 768,
 'B005J61EPA': 769,
 'B005JSV0ZW': 770,
 'B005JZTP16': 771,
 'B005K0HDGE': 772,
 'B005KDG236': 773,
 'B005KJJ4F8': 774,
 'B005KQ5C2K': 775,
 'B005LC0S7W': 776,
 'B005LHQWD6': 777,
 'B005LVV5LQ': 778,
 'B005LVVIIG': 779,
 'B005MAA8LY': 780,
 'B005ME39HU': 781,
 'B005ML0EZS': 782,
 'B005ML3B0S': 783,
 'B005MMO0IY': 784,
 'B005MQWBRC': 785,
 'B005MT03FQ': 786,
 'B005MUEXWE': 787,
 'B005MZN2B2': 788,
 'B005NAUQRY': 789,
 'B005NIY0ZK': 790,
 'B005NSF3ZQ': 791,
 'B005NY4QGM': 792,
 'B005O1BGRQ': 793,
 'B005O315ZW': 794,
 'B005OJF0ZC': 795,
 'B005OLTU8I': 796,
 'B005OMBTKY': 797,
 'B005OQGC1Q': 798,
 'B005OR9H5S': 799,
 'B005OUJGNS': 800,
 'B005P4YED0': 801,
 'B005PRJNCY': 802,
 'B005PRJT9Q': 803,
 'B005Q0X6C8': 804,
 'B005Q22AI2': 805,
 'B005QOX3ZY': 806,
 'B005QOY4FM': 807,
 'B005QPI9ZW': 808,
 'B005R21RIK': 809,
 'B005REXCKE': 810,
 'B005S0V67I': 811,
 'B005S65704': 812,
 'B005SCRR1A': 813,
 'B005SHN43A': 814,
 'B005SHPWQC': 815,
 'B005SJQWI2': 816,
 'B005SZ132Q': 817,
 'B005SZ14O8': 818,
 'B005SZ16L4': 819,
 'B005SZ171I': 820,
 'B005T54I2W': 821,
 'B005T54IAY': 822,
 'B005TA7SFQ': 823,
 'B005UEXG6G': 824,
 'B005UHJE6Y': 825,
 'B005USJ8AK': 826,
 'B005USZYDU': 827,
 'B005V1ZJ72': 828,
 'B005V6BP02': 829,
 'B005VIR5IQ': 830,
 'B005VTVE0U': 831,
 'B005WUVLAG': 832,
 'B005Y0BYE2': 833,
 'B005YRL04Y': 834,
 'B005Z0PYH4': 835,
 'B005Z1RRUU': 836,
 'B005Z5HQNO': 837,
 'B005ZI33HE': 838,
 'B005ZOBNOI': 839,
 'B0060AY6FO': 840,
 'B0060AY7Z8': 841,
 'B0060AY8K2': 842,
 'B0060QM0AG': 843,
 'B0060QM0CY': 844,
 'B0061063ZE': 845,
 'B0061C1N5W': 846,
 'B0061C1NCK': 847,
 'B0061PEAUY': 848,
 'B0061YAUG8': 849,
 'B0062F67L8': 850,
 'B0062OCNX0': 851,
 'B00637B2UQ': 852,
 'B0063PR97I': 853,
 'B0063VBFVI': 854,
 'B0063XH0KQ': 855,
 'B0063Y2OCE': 856,
 'B0064599HK': 857,
 'B0064C3TWE': 858,
 'B0064CL1T2': 859,
 'B0064VVR0Q': 860,
 'B00655KLOY': 861,
 'B00655U3WE': 862,
 'B006564VQC': 863,
 'B0065GC0BA': 864,
 'B0065QV4DU': 865,
 'B0065QV4GW': 866,
 'B0065QVAOI': 867,
 'B0065S8R38': 868,
 'B0066B7JWE': 869,
 'B0066HBGCM': 870,
 'B006ACIMQQ': 871,
 'B006ATJXQW': 872,
 'B006BBLNA8': 873,
 'B006BDR3GY': 874,
 'B006BZIXZM': 875,
 'B006E22IXU': 876,
 'B006E905OW': 877,
 'B006EAMZ62': 878,
 'B006FA7Z8E': 879,
 'B006FBDHG2': 880,
 'B006FDAHZ4': 881,
 'B006GRNYFE': 882,
 'B006GXOS9O': 883,
 'B006H7Z5D2': 884,
 'B006HIR944': 885,
 'B006ICB68O': 886,
 'B006ID6NDQ': 887,
 'B006IE2IO8': 888,
 'B006IE814O': 889,
 'B006IGCAGC': 890,
 'B006JD115K': 891,
 'B006JTTH0U': 892,
 'B006KF645E': 893,
 'B006KY2VZ2': 894,
 'B006L74DMC': 895,
 'B006L8942U': 896,
 'B006LU0GYS': 897,
 'B006M5L5JC': 898,
 'B006MN8HVS': 899,
 'B006N9LFN8': 900,
 'B006NZDO40': 901,
 'B006OBOIPC': 902,
 'B006OOSWRO': 903,
 'B006P3B9MO': 904,
 'B006P5CH1O': 905,
 'B006QD261G': 906,
 'B006R7W2JM': 907,
 'B006RLZVF0': 908,
 'B006RNBI6O': 909,
 'B006ROK1UM': 910,
 'B006SFN4GI': 911,
 'B006SS09A4': 912,
 'B006T2O8TW': 913,
 'B006T3TJIG': 914,
 'B006T8124K': 915,
 'B006TF6WAM': 916,
 'B006UJXG8S': 917,
 'B006V3E272': 918,
 'B006VE6TCW': 919,
 'B006VFZPBW': 920,
 'B006VRXR42': 921,
 'B006WEZ9TK': 922,
 'B006WQRVO4': 923,
 'B006YTTVHO': 924,
 'B006YUTO70': 925,
 'B006YYOJ1W': 926,
 'B006YZ2DFU': 927,
 'B006Z499M0': 928,
 'B006ZN9ZC0': 929,
 'B006ZPRRVY': 930,
 'B00702M3O2': 931,
 'B0070NSPCU': 932,
 'B0070X87PA': 933,
 'B0070XQDRO': 934,
 'B0070Y46UY': 935,
 'B0070ZCA9C': 936,
 'B0071NMK66': 937,
 'B0071NOIWU': 938,
 'B0071VURHW': 939,
 'B0071XO8RA': 940,
 'B00728DYCO': 941,
 'B00728DYEM': 942,
 'B00728DYG0': 943,
 'B00728DYHE': 944,
 'B00728DYP6': 945,
 'B00728DYRO': 946,
 'B0072VFJ8I': 947,
 'B00738TGPC': 948,
 'B0073FTLN2': 949,
 'B0073H86H2': 950,
 'B0073HQ85O': 951,
 'B0073UPPC8': 952,
 'B0073XV3K8': 953,
 'B0073XV7K4': 954,
 'B0074D3CAQ': 955,
 'B0074V3B0Y': 956,
 'B0074V3BKY': 957,
 'B0074VTH2U': 958,
 'B0074VTHBQ': 959,
 'B0074VTHKM': 960,
 'B0074VTHQ6': 961,
 'B00750L9I0': 962,
 'B0075X9KPQ': 963,
 'B007678V5G': 964,
 'B00769T77U': 965,
 'B0076DCJ30': 966,
 'B0076DCT2G': 967,
 'B0076DF3LK': 968,
 'B0076DFB2G': 969,
 'B0076DFC3O': 970,
 'B007712HM4': 971,
 'B0078S9B6G': 972,
 'B0078X0UV6': 973,
 'B0078XG13W': 974,
 'B007978NPG': 975,
 'B007978OY6': 976,
 'B007978PGI': 977,
 'B0079KT81G': 978,
 'B0079XPUOW': 979,
 'B007A4SDCG': 980,
 'B007A4V33M': 981,
 'B007B2IG1A': 982,
 'B007BKQPJ2': 983,
 'B007BSG026': 984,
 'B007E5TVMM': 985,
 'B007ED707W': 986,
 'B007EDCZMW': 987,
 'B007EDYKSE': 988,
 'B007EDYNAO': 989,
 'B007EDYRTQ': 990,
 'B007EDZ08S': 991,
 'B007EECSFA': 992,
 'B007EWJBIE': 993,
 'B007FEFDFQ': 994,
 'B007FG9KU8': 995,
 'B007FG9LIE': 996,
 'B007GBTB0Q': 997,
 'B007GBTBMY': 998,
 'B007GCY8FS': 999,
 ...}

In [258]:
meta_df.iloc[0]['title']

'ROLLING THUNDER: An Historical Novel of War and Politics (Wings of War Book 1)'

In [259]:
ids, scores= model.similar_items(0)

# display the results using pandas for nicer formatting
pd.DataFrame({"Book": meta_df.iloc[ids]['title'], "score": scores})

                                                         Book     score
item_id
B0019LNUVA  ROLLING THUNDER: An Historical Novel of War an...  1.000000
B01GY95VZE                   Weightless: A Small Town Romance  0.785351
B00FJJN0WC  Friends Without Benefits: An Unrequited Love R...  0.746337
B00DQGMT6S          Goliath (A Ryan Mitchell Thriller Book 1)  0.738551
B00KVI9DP4          The Reluctant Midwife: A Hope River Novel  0.712181
B00A2C53M6             The Astronaut Wives Club: A True Story  0.708064
B07MRJG5C9                                A Place Without you  0.701620
B000FCK3C8  The Angel Experiment (Maximum Ride, Book 1): A...  0.699391
B003YL4LYI  A Dance with Dragons (A Song of Ice and Fire, ...  0.689331
B00QZCL7F4  The John Milton Series: Books 4-6 (The John Mi...  0.679169

In [260]:
meta_df[meta_df['author_name'] == 'Brandon Sanderson'].head()

,title,subtitle,description,categories,images,author,image_url,author_name
item_id,,,,,,,,
B00DA6YEKS,"Words of Radiance (The Stormlight Archive, Boo...",Kindle Edition,"[From the Artist, Brandon Sanderson; Read by M...",[ Science Fiction & Fantasy],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51jVA6k9AU...,Brandon Sanderson
B002KYHZHA,Warbreaker,Kindle Edition,"[Review, '""Not only has Sanderson drawn a fres...",[ Science Fiction & Fantasy],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51yNKw2vXS...,Brandon Sanderson
B00VZZ085G,Calamity (The Reckoners Book 3),Kindle Edition,"[Review, 'Praise for the Reckoners series:', #...",[ 'Children\'s eBooks'],[],{'avatar': 'https://m.media-amazon.com/images/...,,Brandon Sanderson
B002GYI9C4,Mistborn: The Final Empire,Kindle Edition,"[Review, '""Elantris', 'is the finest novel of ...",[ Science Fiction & Fantasy],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51G0zeHL2F...,Brandon Sanderson
B0826NKZHR,Rhythm of War: Book Four of The Stormlight Arc...,Kindle Edition,"[Review, Praise for the Stormlight Archive, '“...",[ Science Fiction & Fantasy],[{'large': 'https://m.media-amazon.com/images/...,{'avatar': 'https://m.media-amazon.com/images/...,https://m.media-amazon.com/images/I/51qrprjSJI...,Brandon Sanderson

In [261]:
mistborn_id = bookid_to_idx['B002GYI9C4']

ids, scores= model.similar_items(mistborn_id)
book_ids = [idx_to_bookid[id] for id in ids]

# display the results using pandas for nicer formatting
pd.DataFrame({"Book": meta_df.loc[book_ids]['title'], "score": scores})

                                                         Book     score
item_id
B002GYI9C4                         Mistborn: The Final Empire  1.000000
B000UZQI0Q        The Well of Ascension: Book Two of Mistborn  0.914236
B000FBJCK8           Eragon: Book I (The Inheritance Cycle 1)  0.905808
B002LC8HF0           The Hero of Ages: Book Three of Mistborn  0.896956
B003P2WO5E  The Way of Kings (The Stormlight Archive, Book 1)  0.890302
B00HBQWGYO                 Half a King (Shattered Sea Book 1)  0.880805
B00H25FCNG               The Broken Eye (Lightbringer Book 3)  0.879732
B003JTHY76              The Black Prism (Lightbringer Book 1)  0.872897
B00ARHAAZ6                  Steelheart (The Reckoners Book 1)  0.858499
B003G93YLY  Elantris: Tenth Anniversary Author's Definitiv...  0.855019

## Entrenar modelo con Surprise

In [41]:
from surprise import Dataset, SVD, Reader, accuracy
from surprise.model_selection import train_test_split

In [29]:
reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(reviews_df[['user_id', 'item_id', 'rating']], reader)

In [48]:
trainset, testset = train_test_split(data, test_size=0.2, random_state=42)

In [49]:
algo = SVD()
algo.fit(trainset)

In [50]:
predictions = algo.test(testset)

In [51]:
accuracy.rmse(predictions)

RMSE: 0.7607

0.7607130593338862

In [52]:
df_test = pd.DataFrame(testset, columns=['user_id', 'item_id', 'rating_real'])
df_test.to_csv('testset_oraculo.csv', index=False)

In [35]:
import joblib

In [55]:
joblib.dump(algo, 'svd_model.pkl')

['svd_model.pkl']

## Generar embeddings de los libros

In [6]:
from sentence_transformers import SentenceTransformer

In [2]:
books_df = pd.read_csv('kindle_meta_cleaned.csv')
books_df.head()

,item_id,title,subtitle,description,categories,images
0,B094XQFL8P,Runaway (Empire High Book 5),Kindle Edition,"[About the Author, 'Ivy Smoak is the internati...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...
1,B075WQK8ZJ,Unsheltered: A Novel,Kindle Edition,"[Amazon.com Review, 'An Amazon Best Book of Oc...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...
2,B09JS55FW3,Reaper (Cradle Book 10),Kindle Edition,"[About the Author, Will Wight, 'lives in Flori...",[ Science Fiction & Fantasy],[{'large': 'https://m.media-amazon.com/images/...
3,B01JJ5CURW,To-Do List Formula: A Stress-Free Guide To Cre...,Kindle Edition,[],[ Business & Money],[{'large': 'https://m.media-amazon.com/images/...
4,B00KQBTC3O,Shopping for a Billionaire 1 (Shopping for a B...,Kindle Edition,"[From the Author, 'Please sign up for my New R...",[ Literature & Fiction],[{'large': 'https://m.media-amazon.com/images/...

In [15]:
# Título y categorías primeros, luego descripción. Esto es porque la descripción suele ser más larga y menos importante, por lo que el modelo la puede truncar por el número máximo de tokens.
books_df['complete_text'] = books_df['title'].fillna('') + books_df['categories'].fillna('') + books_df['description'].fillna('')

In [16]:
books_df.iloc[0].complete_text

"Runaway (Empire High Book 5)[  Literature & Fiction][About the Author, 'Ivy Smoak is the international bestselling author of The Hunted Series. Her books have sold over 1 million copies worldwide, and her latest release, Empire High Betrayal, hit #4 in the entire Kindle store. When she\\'s not writing, you can find Ivy binge watching too many TV shows, taking long walks, playing outside, and generally refusing to act like an adult. She lives with her husband in Delaware.', --This text refers to the, hardcover, edition.]"

Ver largo del texto

In [17]:
books_df['text_length'] = books_df['complete_text'].apply(lambda x: len(x.split()))

In [18]:
books_df[['item_id', 'complete_text', 'text_length']].head()

      item_id                                      complete_text  text_length
0  B094XQFL8P  Runaway (Empire High Book 5)[  Literature & Fi...           85
1  B075WQK8ZJ  Unsheltered: A Novel[  Literature & Fiction][A...         1587
2  B09JS55FW3  Reaper (Cradle Book 10)[  Science Fiction & Fa...           96
3  B01JJ5CURW  To-Do List Formula: A Stress-Free Guide To Cre...           15
4  B00KQBTC3O  Shopping for a Billionaire 1 (Shopping for a B...          138

In [20]:
books_df['text_length'].describe()

count     4601.000000
mean      1314.534232
std       2290.880745
min          3.000000
25%        135.000000
50%        405.000000
75%       1514.000000
max      43958.000000
Name: text_length, dtype: float64

In [21]:
nlp_model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [25]:
# Probar el modelo
sentence = "This is an example sentence"
embedding = nlp_model.encode(sentence)
print(embedding)

[ 0.18845688  0.17425634  0.0544778   0.29051757  0.16766414 -0.04720675
  0.6455802   0.1598089   0.22689255 -0.03089058  0.2558835  -0.05258775
 -0.2261015  -0.05710635  0.13042626  0.12495356  0.31749612  0.19444402
 -0.5863256  -0.01258597  0.6099092   0.16432735  0.03331115 -0.27383068
 -0.28975752 -0.21119711 -0.02261387 -0.17035921  0.1615901   0.06082748
 -0.24162416  0.18579195  0.4274097   0.19295172 -0.07234465  0.16611089
  0.10442799  0.20477234  0.21116723  0.19973989 -0.09408262 -0.1738367
  0.06427368  0.28025475 -0.29530594  0.0620954   0.10427695 -0.02364418
  0.1291318  -0.12617467 -0.17899004  0.0370057  -0.6125061   0.05029812
  0.17730357  0.22494122  0.17386065 -0.03840291 -0.2128681   0.2584925
 -0.12101632  0.30971512 -0.41966376  0.00907662  0.14188907 -0.30556947
  0.17621145 -0.07087357 -0.62033135  0.6770835   0.01723751  0.18405128
 -0.1678578   0.20452645 -0.1477028  -0.06175363  0.63017434  0.11120182
  0.0515306   0.15927422 -0.05370894  0.05350953  0.14135505  0.11239237
 -0.48411807 -0.16993625 -0.05321806  0.27650332  0.11777699 -0.3491253
 -0.51375544 -0.3284404   0.54240453 -0.05326695  0.22918333 -0.01275975
  0.10331826 -0.33627796  0.24764974  0.8155242  -0.08930914  0.24757893
 -0.12043507  0.01898992  0.32457092 -0.2616242  -0.19714794  0.01440966
 -0.03558918 -0.32742974 -0.04829868  0.18030524  0.02312142 -0.14245255
 -0.1952391  -0.5549117   0.04146009 -0.08038604 -0.12909935  0.34541157
  0.04179804 -0.17788367  0.3445857   0.10763667  0.0064131  -0.8081874
  0.1831181  -0.06116288  0.10278969 -0.35960677 -0.121007   -0.31905478
  0.14434484  0.19774662 -0.04758298 -0.13626693  0.2791588   0.10766133
 -0.03404968  0.06557176  0.03390289  0.47428304  0.03201588  0.43823123
 -0.18881223  0.39110145 -0.2936494  -0.09019411 -0.08186887  0.1528505
  0.1180672  -0.2978689   0.18289228 -0.23518273 -0.04338413 -0.08308792
 -0.01447853  0.08936623  0.11753748 -0.06312167 -0.13069405  0.16051388
 -0.07993037  0.04523428 -0.11637421 -0.19606252  0.03943988 -0.34911755
 -0.01147579  0.26085484  0.31661978 -0.08063631 -0.18066707  0.02020098
 -0.08835123 -0.01678056 -0.3813459   0.15447439 -0.03228498  0.01385774
  0.31472567 -0.29187736 -0.11789729 -0.02333079 -0.22907734  0.2485081
 -0.08262311  0.17519872  0.07053153  0.17890441 -0.19748044  0.11594962
  0.2295772   0.08844829 -0.34138513 -0.00305387  0.44035342  0.20765047
 -0.23839882  0.14549935 -0.32511145 -0.04974955  0.0841229  -0.2610328
  0.4220679  -0.27341735  0.22958674 -0.18960795 -0.17343746 -0.04636104
  0.12553105  0.47853258 -0.55295616  0.21560635  0.06972308  0.07278685
 -0.2389016   0.19889085 -0.4235428  -0.1645273  -0.22758175 -0.04920294
  0.23738696 -0.4553153  -0.06247041  0.5811022  -0.08885646 -0.05396935
  0.2865534  -0.48124048 -0.06124141 -0.28116295  0.36897904 -0.2953122
 -0.71865684 -0.38774467 -0.16324672  0.13904098 -0.02087943 -0.05228813
 -0.10613579 -0.0552915  -0.0638025   0.02985425  0.01341955  0.01263426
  0.11067462 -0.07000601 -0.01710513  0.10809219 -0.11134928 -0.42874828
 -0.33341154  0.14569521 -0.24261558  0.15181307 -0.08179666  0.24336219
 -0.37745434  0.0814958   0.09220827 -0.27653462  0.04063629  0.2000225
 -0.04784402 -0.40510845  0.18088548  0.08081245  0.02778463  0.14977634
 -0.4525285  -0.06112524  0.22713466 -0.13096137 -0.2984912  -0.15302697
 -0.2612384  -0.221886    0.04267638 -0.20062749 -0.02200276 -0.49436882
  0.53533363 -0.02982702 -0.0196263   0.05706297  0.17869137  0.31158468
  0.3637424   0.2113454  -0.39374962  0.17488782  0.0114086  -0.10499533
 -0.14383784 -0.10661031 -0.4385613   0.04653317 -0.26895502 -0.03211481
  0.31267285 -0.28747168 -0.30524966 -0.02647275  0.25250226 -0.18864204
  0.2102422   0.07654757 -0.3165551   0.13155583 -0.02851386  0.26622102
 -0.43981522  0.33574787 -0.02058763 -0.22813609 -0.18404217  0.1512935
 -0.20930645 -0.45565373  0.09736753 -0.17393908 -0.12940058 -0.11562895
  0.27910298 -0.15251724  0.1635363  -0.1845058  -0.00569292 -0.30151084
 -0.10034245  0.33604613 -0.01101645  0.01471762 -0.07627986  0.7871474
 -0.28120595 -0.238199    0.10064662  0.5990075   0.5006777   0.15818903
 -0.29037476  0.06542083 -0.14885974  0.06843906 -0.03958026  0.14649299
 -0.14633441  0.17913018  0.28052384  0.36252975 -0.31337696 -0.04091793
 -0.07653161  0.1532358   0.19257896 -0.37365276  0.09541661 -0.28398472
 -0.00148433 -0.04926245  0.44722313  0.657747    0.16523835  0.05867769
 -0.40437827 -0.07801348 -0.2553785  -0.36102325 -0.0967814  -0.14205822
  0.1474618   0.09517752  0.05682942 -0.1747828   0.26147893  0.14114739
  0.12460978  0.08857512  0.18453881  0.2709024   0.34769505  0.08729656]

In [26]:
nlp_model.max_seq_length = 256

In [32]:
text_list = books_df['complete_text'].tolist()
vectors = nlp_model.encode(text_list, show_progress_bar=True)

Batches:   0%|          | 0/144 [00:00<?, ?it/s]

In [33]:
embeddings_dict = {
    item_id: vector 
    for item_id, vector in zip(books_df['item_id'], vectors)
}

In [36]:
joblib.dump(embeddings_dict, 'book_embeddings.pkl')

['book_embeddings.pkl']